      SUBROUTINE  CANRES

      INCLUDE 'modvars.h'

      EMBAR =  9999
      RESIST = 9999
      IF (F. GT. 0.)  THEN

CC      SUBROUTINE COMPUTES CANOPY RESISTANCE (RESIST)
CC      AND MOISTURE AVAILABILITY (EMBAR)
CC      FOR TOTAL VEGETATION AND BARE SOIL CANOPY
CC         ***** RESISTANCES CONVERTED TO CGS (S CM-1) *****

        RCBS = (SUMW - F*SUMW)/F
CC       RCBS IS CANOPY RESISTANCE FOR BARE SOIL


	  IF(XLEF. NE. 0. AND. CHA. NE. 0. AND.  OSHUM. NE. QD(1)) THEN

	CELL1 = (1./CHA + RZASCR)
	QSTVEG = 10**( 6.1989 - ( 2353. / OTEMP ) )
        CELL2 = (QSTVEG - QD(1))
        CELL3 = DENS*LE

CC    EMP IS MOISTURE AVAILABILITY FOR VEGETATION CANOPY
CC    EPOTV IS POTENTIAL EVAPORATION OVER VEGETATION
CC    RCP IS THE CANOPY RESISTANCE FOR VEGETATION

        EPOTV = CELL3*CELL2/CELL1
	EMP  = XLEF/EPOTV
        RCP = (CELL1 - EMP*CELL1)/EMP

        RESIST = RCP*FRVEG   +  RCBS*(1.0 - FRVEG)

CC     WEIGHT TOTAL CANOPY RESISTANCE, MAVAIL BY VEG FRACTION

        EMBAR = EMP*FRVEG + F*(1.0 - FRVEG)

         END IF

       END IF

      RETURN

      END


