subroutine  CANRES
  use simsphere_mod
  implicit none

  real :: RCBS=0.0, CELL1=0.0, CELL2=0.0, CELL3=0.0, QSTVEG=0.0
  real :: EPOTV=0.0, EMP=0.0, RCP=0.0

!      INCLUDE 'modvars.h'

  EMBAR =  9999
  RESIST = 9999
  IF (F > 0.)  THEN

!      SUBROUTINE COMPUTES CANOPY RESISTANCE (RESIST)
!      AND MOISTURE AVAILABILITY (EMBAR)
!      FOR TOTAL VEGETATION AND BARE SOIL CANOPY
!         ***** RESISTANCES CONVERTED TO CGS (S CM-1) *****

    RCBS = (SUMW - F*SUMW)/F
!       RCBS IS CANOPY RESISTANCE FOR BARE SOIL


    IF(XLEF /= 0 .AND. CHA /= 0 .AND. OSHUM /= QD(1)) THEN

      CELL1 = (1./CHA + RZASCR)
      QSTVEG = 10**( 6.1989 - ( 2353. / OTEMP ) )
      CELL2 = (QSTVEG - QD(1))
      CELL3 = DENS*LE

!    EMP IS MOISTURE AVAILABILITY FOR VEGETATION CANOPY
!    EPOTV IS POTENTIAL EVAPORATION OVER VEGETATION
!    RCP IS THE CANOPY RESISTANCE FOR VEGETATION

      EPOTV = CELL3*CELL2/CELL1
      EMP  = XLEF/EPOTV
      RCP = (CELL1 - EMP*CELL1)/EMP

      RESIST = RCP*FRVEG   +  RCBS*(1.0 - FRVEG)

!     WEIGHT TOTAL CANOPY RESISTANCE, MAVAIL BY VEG FRACTION

      EMBAR = EMP*FRVEG + F*(1.0 - FRVEG)

    end if

  end if

  return
end

